### ISSUE TITLE
Allow for arbitrary array size with custom element assertions

### ISSUE THREAD

**Issue by crizzis** [zendesk/jazon#18]
It is currently possible to run verifications on an array like so: 

`products: [{id: { it > 0}}, {id: { it > 0}}]`

This syntax, however, only allows for a specific, fixed number of elements in the array (2 in the example above). 

It would be a nice feature if we could also do sth along the lines of: 

`products: anyNumberOf({id: { it >0 }})`

where each array element would still be validated against the condition, but the array size could be arbitrary. 

Currently, the workaround is to use `products: { it.every { <some_condition_that_needs_to_hold_for_every_element>} }`. The problem is, the 'JSON map' syntax cannot be used inside `<some_condition_that_needs_to_hold_for_every_element>`, so it's not exactly readable for more complex objects.

**Comment by pawel-mikolajczyk** [comment]
This is a great idea :) I do not remember my own need for such assertions (when number of elements in not predictable) but this sounds like a valid case.

The effort to implement this seems easy so you can expect this very soon. I will keep you updated :) 
Or - if you would like to fix it yourself - do not hesitate. I can help to point out which part of code needs extending. 
After thinking about better name for that method I find the name you have proposed a perfect one :)

One last remark: 
Your issue description is a little bit confusing - it seems you are using `{}` as syntax of Groovy's map while `[]` is the correct one (`{id: { it > 0}}` instead of `[id: { it > 0}]`). I know it is easy to mistake this with JSON syntax 😛

**Comment by crizzis** [comment]
Thanks for the response. You're absoolutely right about the syntax mixup, I was thinking in JSON terms writing the example 😛

What I managed to figured out is that `SpockExpectationFactory` would need to handle some special marker type that `anyNumberOf` would return (alongside `List` and `Set`) by returning a custom `JsonExpectation`, similar to `UnorderedArrayExpectation` (not sure if the junit module could somehow be adjusted to support a similar functionality - haven't really looked at the code). If this was also your idea of implementation, I can have a go at it after the weekend.

**Comment by pawel-mikolajczyk** [comment]
You are mostly right:
1. It is best to add a test similar to: https://github.com/zendesk/jazon/blob/master/jazon-core/src/test/groovy/com/zendesk/jazon/MatcherSpec.groovy#L239
2. As you mentioned, you need to add a new implementation of `JsonExpectation` interface. It is best take `UnorderedArrayExpectation` or `OrderedArrayExpectation` as examples.
3. It needs to be someway pinned in `SpockExpectationFactory`. I think it is best to add a if-statement that passes through the given `object` if it is already an `JsonExpectation`:
```
if (object instanceof JsonExpectation) {
    return object;
} ...
```
4. As you have mentioned, you need some public factory method `anyNumberOf()` constructing the your-new-`JsonExpectation` directly.

**Comment by crizzis** [comment]
@pawel-mikolajczyk see related PR. 

I couldn't find a way to avoid the additional marker type (see [comment](https://github.com/zendesk/jazon/pull/19#discussion_r369278273)). If you know a way to work around that issue, feel free to amend the PR.

**Comment by pawel-mikolajczyk** [comment]
@crizzis You are right :) The marker type is a very good idea. I have also replied to your comment in the PR (https://github.com/zendesk/jazon/pull/19#discussion_r371028704)

**Comment by crizzis** [comment]
See updated PR
